<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.24.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OnlineCourses.Core\OnlineCourses.Core.csproj" />
    <ProjectReference Include="..\OnlineCourses.Infrastructure\OnlineCourses.Infrastructure.csproj" />
    <ProjectReference Include="..\OnlineCourses.MongoMigration\OnlineCourses.MongoMigration.csproj" />
  </ItemGroup>
</Project>
